language: node_js
node_js:
  - '4'
sudo: required
cache:
  directories:
    - node_modules
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - COVERAGE=true ember test
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
install:
  - npm install
  - bower install
script:
  - 'ember try:each'
after_script:
  - codeclimate-test-reporter < lcov.dat
  - cat lcov.dat | node_modules/coveralls/bin/coveralls.js
dist: trusty
